version: "3.8"

services:
  apache2-php:
    build:
      dockerfile: Dockerfile
    restart: 'no'
    volumes:
      - ..:/workspace:cached # Your code
      - ~/.ssh:/home/vscode/.ssh:cached # Your SSH keys if you use a custom git+ssh repo
    ports:
      - '80'

  postgresql:
    image: postgres:14.5-bullseye
    restart: 'no'
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.0.4-alpine3.16
    restart: 'no'
    ports:
      - '6379'
